/*
 * APCREATIONZ Portfolio - script.js
 * Description: Handles all interactive JavaScript for the APCREATIONZ modern developer portfolio.
 * Author: APCREATIONZ (Generated by AI)
 * Date: 2024-03-20
 *
 * Includes: Loading screen, custom cursor, smooth scrolling, navbar effects,
 * hamburger menu, typewriter effect, parallax, scroll animations (Intersection Observer),
 * stats counter, back-to-top button, and particles.js initialization.
 */

document.addEventListener('DOMContentLoaded', () => {
    // --- Configuration Variables (Easily editable) ---
    const config = {
        roles: ["Python Developer", "Creative Builder", "AI Enthusiast"],
        typewriterSpeed: 100, // typing speed in ms
        typewriterDeleteSpeed: 50, // deleting speed in ms
        typewriterDelay: 2000, // delay before typing next role
        parallaxIntensity: 26, // max px movement for parallax elements
        revealOffset: '10%', // Offset for Intersection Observer
        emailServiceUrl: 'https://formspree.io/f/xzdwkqvg',
        particlesConfig: { // Configuration for particles.js
            "particles": {
              "number": {
                "value": 80,
                "density": {
                  "enable": true,
                  "value_area": 800
                }
              },
              "color": {
                "value": ["#00e0ff", "#aaff00", "#ff00ea"]
              },
              "shape": {
                "type": "circle",
                "stroke": {
                  "width": 0,
                  "color": "#000000"
                },
                "polygon": {
                  "nb_sides": 5
                }
              },
              "opacity": {
                "value": 0.5,
                "random": false,
                "anim": {
                  "enable": false,
                  "speed": 1,
                  "opacity_min": 0.1,
                  "sync": false
                }
              },
              "size": {
                "value": 3,
                "random": true,
                "anim": {
                  "enable": false,
                  "speed": 40,
                  "size_min": 0.1,
                  "sync": false
                }
              },
              "line_linked": {
                "enable": true,
                "distance": 150,
                "color": "#0a0a0f", // Match background for subtle effect
                "opacity": 0.4,
                "width": 1
              },
              "move": {
                "enable": true,
                "speed": 2,
                "direction": "none",
                "random": false,
                "straight": false,
                "out_mode": "out",
                "bounce": false,
                "attract": {
                  "enable": false,
                  "rotateX": 600,
                  "rotateY": 1200
                }
              }
            },
            "interactivity": {
              "detect_on": "canvas",
              "events": {
                "onhover": {
                  "enable": true,
                  "mode": "grab"
                },
                "onclick": {
                  "enable": true,
                  "mode": "push"
                },
                "resize": true
              },
              "modes": {
                "grab": {
                  "distance": 140,
                  "line_linked": {
                    "opacity": 1
                  }
                },
                "bubble": {
                  "distance": 400,
                  "size": 40,
                  "duration": 2,
                  "opacity": 8,
                  "speed": 3
                },
                "repulse": {
                  "distance": 200,
                  "duration": 0.4
                },
                "push": {
                  "particles_nb": 4
                },
                "remove": {
                  "particles_nb": 2
                }
              }
            },
            "retina_detect": true
          }
    };

    // --- Loading Screen ---
    const loadingScreen = document.getElementById('loading-screen');
    window.addEventListener('load', () => {
        loadingScreen.classList.add('hidden');
        // Ensure it's removed after transition for accessibility/performance
        loadingScreen.addEventListener('transitionend', () => {
            loadingScreen.remove();
        });
    });

    // --- Custom Cursor Glow ---
    const cursorGlow = document.createElement('div');
    cursorGlow.classList.add('cursor-glow');
    document.body.appendChild(cursorGlow);

    document.addEventListener('mousemove', e => {
        cursorGlow.style.left = `${e.clientX}px`;
        cursorGlow.style.top = `${e.clientY}px`;
    });

    document.querySelectorAll('a, button, .btn, .project-card, .skill-item, .social-link, input, textarea, .hamburger-menu').forEach(el => {
        el.addEventListener('mouseenter', () => cursorGlow.classList.add('hovered'));
        el.addEventListener('mouseleave', () => cursorGlow.classList.remove('hovered'));
    });


    // --- Navbar Scroll Effect ---
    const navbar = document.getElementById('navbar');
    let lastScrollY = window.scrollY;

    window.addEventListener('scroll', () => {
        // Sticky Navbar background change
        if (window.scrollY > 50) {
            navbar.classList.add('scrolled');
        } else {
            navbar.classList.remove('scrolled');
        }

        // Hide/show navbar on scroll down/up (optional, as it's sticky transparent)
        // if (window.scrollY > lastScrollY && window.scrollY > 200) {
        //     navbar.style.transform = 'translateY(-100%)';
        // } else {
        //     navbar.style.transform = 'translateY(0)';
        // }
        // lastScrollY = window.scrollY;

        updateScrollProgress();
        updateActiveNavLink();
    });

    // --- Smooth Scroll Navigation ---
    document.querySelectorAll('nav a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const targetId = this.getAttribute('href');
            document.querySelector(targetId).scrollIntoView({
                behavior: 'smooth'
            });

            // Close mobile menu after clicking a link
            if (document.body.classList.contains('nav-open')) {
                document.body.classList.remove('nav-open');
            }
        });
    });

    // --- Mobile Hamburger Menu ---
    const hamburgerMenu = document.querySelector('.hamburger-menu');
    hamburgerMenu.addEventListener('click', () => {
        document.body.classList.toggle('nav-open');
    });

    // --- Typewriter Effect in Hero Section ---
    const typewriterTextElement = document.getElementById('typewriter-text');
    let roleIndex = 0;
    let charIndex = 0;
    let isDeleting = false;

    function typeWriterEffect() {
        if (!typewriterTextElement) return;
        const currentRole = config.roles[roleIndex];
        let displayText = currentRole.substring(0, charIndex);
        typewriterTextElement.textContent = displayText;

        if (!isDeleting) {
            charIndex++;
            if (charIndex > currentRole.length) {
                isDeleting = true;
                setTimeout(typeWriterEffect, config.typewriterDelay);
                return;
            }
        } else {
            charIndex--;
            if (charIndex < 0) {
                isDeleting = false;
                roleIndex = (roleIndex + 1) % config.roles.length;
                setTimeout(typeWriterEffect, 500); // Short delay before typing next
                return;
            }
        }
        setTimeout(typeWriterEffect, isDeleting ? config.typewriterDeleteSpeed : config.typewriterSpeed);
    }
    
    typeWriterEffect();

    // --- Intersection Observer for Reveal Animations ---
    const revealElements = document.querySelectorAll('.reveal');

    const observerOptions = {
        root: null, // viewport
        rootMargin: config.revealOffset, // When 10% of element is in view
        threshold: 0.1
    };

    const observer = new IntersectionObserver((entries, observer) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('active');
                // For progress bars, trigger animation on reveal
                entry.target.querySelectorAll('.progress-bar').forEach(bar => {
                    const width = bar.style.width; // Get target width from inline style
                    bar.style.width = '0%'; // Reset to 0
                    requestAnimationFrame(() => { // Re-apply after next render cycle
                        bar.style.width = width;
                    });
                });
                observer.unobserve(entry.target); // Unobserve once animated
            }
        });
    }, observerOptions);

    revealElements.forEach(el => {
        observer.observe(el);
    });

    // Initialize progress bars (ensure they are 0% initially before JS takes over)
    document.querySelectorAll('.progress-bar').forEach(bar => {
        bar.style.width = '0%';
    });


    // --- Stats Counter Animation ---
    const statNumbers = document.querySelectorAll('.stat-number');

    const counterObserverOptions = {
        root: null,
        rootMargin: '0px',
        threshold: 0.5 // Trigger when 50% of the element is visible
    };

    const counterObserver = new IntersectionObserver((entries, observer) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                const target = entry.target;
                const endValue = parseInt(target.dataset.target);
                let startValue = 0;
                const duration = 2000; // 2 seconds
                const increment = endValue / (duration / 16); // ~60fps

                const updateCounter = () => {
                    startValue += increment;
                    if (startValue < endValue) {
                        target.textContent = Math.ceil(startValue);
                        requestAnimationFrame(updateCounter);
                    } else {
                        target.textContent = endValue;
                    }
                };
                updateCounter();
                observer.unobserve(target); // Stop observing once counted
            }
        });
    }, counterObserverOptions);

    statNumbers.forEach(num => {
        counterObserver.observe(num);
    });


    // --- Scroll Progress Indicator ---
    const scrollProgress = document.getElementById('scroll-progress');
    function updateScrollProgress() {
        const totalHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
        const progress = (window.scrollY / totalHeight) * 100;
        scrollProgress.style.width = `${progress}%`;
    }

    // --- Back to Top Button ---
    const backToTopBtn = document.getElementById('back-to-top');
    window.addEventListener('scroll', () => {
        if (window.scrollY > 300) { // Show button after scrolling 300px
            backToTopBtn.classList.add('show');
        } else {
            backToTopBtn.classList.remove('show');
        }
    });

    backToTopBtn.addEventListener('click', () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });

    // --- Active Navigation Link on Scroll ---
    const sections = document.querySelectorAll('section');
    const navLinks = document.querySelectorAll('.nav-links a');

    function updateActiveNavLink() {
        let current = '';
        sections.forEach(section => {
            const sectionTop = section.offsetTop;
            const sectionHeight = section.clientHeight;
            // Adjust for navbar height
            if (window.scrollY >= sectionTop - navbar.offsetHeight - 50) {
                current = section.getAttribute('id');
            }
        });

        navLinks.forEach(link => {
            link.classList.remove('active');
            if (link.getAttribute('href').includes(current)) {
                link.classList.add('active');
            }
        });
    }

    // Initial call for active link on load
    updateActiveNavLink();


    // --- Project Carousel Logic ---
    const carouselItems = document.querySelectorAll('.carousel-item');
    const prevBtn = document.querySelector('.prev-btn');
    const nextBtn = document.querySelector('.next-btn');
    const pagination = document.querySelector('.carousel-pagination');
    let currentIndex = 0;

    function updateCarousel() {
        carouselItems.forEach((item, index) => {
            item.classList.remove('active', 'prev', 'next');
            
            if (index === currentIndex) {
                item.classList.add('active');
            } else if (index === (currentIndex - 1 + carouselItems.length) % carouselItems.length) {
                item.classList.add('prev');
            } else if (index === (currentIndex + 1) % carouselItems.length) {
                item.classList.add('next');
            }
        });

        // Update pagination dots
        const dots = document.querySelectorAll('.dot');
        dots.forEach((dot, index) => {
            dot.classList.toggle('active', index === currentIndex);
        });
    }

    if (carouselItems.length > 0) {
        // Create dots
        carouselItems.forEach((_, index) => {
            const dot = document.createElement('div');
            dot.classList.add('dot');
            if (index === 0) dot.classList.add('active');
            dot.addEventListener('click', () => {
                currentIndex = index;
                updateCarousel();
            });
            pagination.appendChild(dot);
        });

        nextBtn.addEventListener('click', () => {
            currentIndex = (currentIndex + 1) % carouselItems.length;
            updateCarousel();
        });

        prevBtn.addEventListener('click', () => {
            currentIndex = (currentIndex - 1 + carouselItems.length) % carouselItems.length;
            updateCarousel();
        });

        // Drag/Swipe Support
        let startX = 0;
        let isDragging = false;
        const track = document.querySelector('.carousel-track');

        const handleStart = (e) => {
            isDragging = true;
            startX = e.type === 'touchstart' ? e.touches[0].clientX : e.clientX;
        };

        const handleEnd = (e) => {
            if (!isDragging) return;
            isDragging = false;
            const endX = e.type === 'touchend' ? e.changedTouches[0].clientX : e.clientX;
            const diff = startX - endX;

            if (Math.abs(diff) > 50) {
                if (diff > 0) {
                    currentIndex = (currentIndex + 1) % carouselItems.length;
                } else {
                    currentIndex = (currentIndex - 1 + carouselItems.length) % carouselItems.length;
                }
                updateCarousel();
            }
        };

        track.addEventListener('mousedown', handleStart);
        track.addEventListener('mouseup', handleEnd);
        track.addEventListener('touchstart', handleStart);
        track.addEventListener('touchend', handleEnd);

        updateCarousel(); // Initial call
    }


    // --- Contact Form Submission ---
    const contactForm = document.getElementById('contact-form');
    const formStatus = document.getElementById('form-status');

    if (contactForm) {
        const submitButton = contactForm.querySelector('.send-btn');
        const defaultButtonText = submitButton ? submitButton.textContent : '';

        contactForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            formStatus.textContent = '';
            formStatus.classList.remove('success', 'error');
            if (submitButton) {
                submitButton.disabled = true;
                submitButton.classList.add('is-loading');
                submitButton.textContent = 'Sending...';
            }

            const formData = new FormData(contactForm);

            try {
                const response = await fetch(contactForm.action || config.emailServiceUrl, {
                    method: contactForm.method || 'POST',
                    headers: {
                        'Accept': 'application/json'
                    },
                    body: formData
                });

                if (response.ok) {
                    formStatus.textContent = 'Message sent successfully!';
                    formStatus.classList.add('success');
                    contactForm.reset();
                } else {
                    const data = await response.json().catch(() => null);
                    formStatus.textContent = data?.errors ? data.errors.map(error => error.message).join(', ') : 'Unable to send message right now.';
                    formStatus.classList.add('error');
                }
            } catch (error) {
                formStatus.textContent = 'Unable to send message right now.';
                formStatus.classList.add('error');
                console.error('Form submission error:', error);
            } finally {
                if (submitButton) {
                    submitButton.disabled = false;
                    submitButton.classList.remove('is-loading');
                    submitButton.textContent = defaultButtonText;
                }
            }
        });
    }

    // Initial calls on page load
    updateScrollProgress();
});
